[package]
name = "glang"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
assert_matches = "1.5.0"
rstest = "0.18.2"

[dependencies]
clap = { version = "4.5.1", features = ["cargo"] }
toml = "0.8.10"
